// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/jquery.cookie/jquery.cookie.d.ts

interface JQuery {
    maskMoney(maskMoneyOption?:any);
}

declare module "jquery.maskMoney" {}